### PR TITLE
fix(frontend): route agent checks to gateway

### LINKED ISSUE #1518: Deerflow Agent "Could not verify name availability - please try again"
I am trying to create a new Deerflow agent, and its not even letting me past the "name" stage. It doesn't matter what I name it, it returns a "Could not verify name availability — please try again" Error, and I cannot get past this stage of creating an agent, therefore I can't create an agent. I have tried long and short usernames, unique ones too, nothing will get me past this step. 

Image

### PR DESCRIPTION
**Pull request by LittleChenLiya**
## Summary
- route local `/api/agents/*` requests to the gateway when `NEXT_PUBLIC_BACKEND_BASE_URL` is unset
- route local `/api/langgraph/*` requests to the LangGraph server when `NEXT_PUBLIC_LANGGRAPH_BASE_URL` is unset
- show a clearer error when agent name checks cannot reach the backend

Closes #1518

## Validation
- `corepack pnpm exec eslint . --ext .ts,.tsx`
- `corepack pnpm exec tsc --noEmit`
- `BETTER_AUTH_SECRET=local-dev-secret corepack pnpm exec next build`

### CODE REVIEW

File: frontend/src/core/i18n/locales/zh-CN.ts [hunk 1]
```diff
@@ -181,7 +181,8 @@ export const zhCN: Translations = {
     nameStepContinue: "继续",
     nameStepInvalidError: "名称无效，只允许字母、数字和连字符",
     nameStepAlreadyExistsError: "已存在同名智能体",
-    nameStepCheckError: "无法验证名称可用性，请稍后重试",
+    nameStepCheckError:
+      "\u65e0\u6cd5\u8fde\u63a5 DeerFlow \u540e\u7aef\u6765\u9a8c\u8bc1\u540d\u79f0\u662f\u5426\u53ef\u7528\u3002\u8bf7\u5148\u542f\u52a8\u540e\u7aef\uff0c\u6216\u914d\u7f6e NEXT_PUBLIC_BACKEND_BASE_URL\uff0c\u7136\u540e\u518d\u91cd\u8bd5\u3002",
```
Comment (WillemJiang) [inline frontend/src/core/i18n/locales/zh-CN.ts]: Please update your editor to turn the UTF-8 codes into Chinese.

File: frontend/next.config.js [hunk 2]
```diff
@@ -11,13 +11,21 @@ const config = {
...
       rewrites.push({
         source: "/api/langgraph/:path*",
         destination: "http://127.0.0.1:2024/:path*",
       });
     }
 
     if (!process.env.NEXT_PUBLIC_BACKEND_BASE_URL) {
+      rewrites.push({
+        source: "/api/agents",
+        destination: "http://127.0.0.1:8001/api/agents",
```
Comment (WillemJiang) [inline frontend/next.config.js]: It may not work in the Docker environment.
